const $=s=>document.querySelector(s);const CONTENT_PATH='data/content.json';let data=null,sha=null,tab='profile',dirty=false,pendingUploads=new Map();const tabs=[['profile','基本资料'],['sidebar','履历与研究'],['news','新闻动态'],['papers','代表论文'],['projects','科研项目'],['students','学生培养'],['join','招生信息']];
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));const get=path=>path.split('.').reduce((o,k)=>o?.[k],data);const set=(path,v)=>{const ks=path.split('.');let o=data;ks.slice(0,-1).forEach(k=>o=o[k]);o[ks.at(-1)]=v;markDirty()};
function toast(msg){$('#toast').textContent=msg;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2200)}function markDirty(){dirty=true;$('#dirtyState').textContent='有尚未发布的修改'}
function field(path,label,type='text',hint=''){const val=get(path);return `<div class="field"><label>${label}${type==='textarea'?`<textarea data-path="${path}">${esc(val)}</textarea>`:`<input data-path="${path}" type="${type}" value="${esc(val)}">`}</label>${hint?`<small>${hint}</small>`:''}</div>`}
function imageField(path,label){const val=get(path);return `<div class="field"><label>${label}</label><div class="image-row"><div><input data-path="${path}" value="${esc(val)}" placeholder="图片网址或仓库内路径"><input type="file" accept="image/*" data-upload="${path}"><small>可粘贴图片网址，或选择图片后随内容一起上传。</small></div>${val?`<img class="image-preview" src="${esc(val)}" alt="预览">`:`<div class="image-preview"></div>`}</div></div>`}
function repeater(key,title,fields){return data[key].map((item,i)=>`<section class="repeater"><h3>${title} ${i+1}</h3><button class="remove" type="button" data-remove="${key}.${i}">删除</button>${fields.map(([name,label,type])=>type==='image'?imageField(`${key}.${i}.${name}`,label):field(`${key}.${i}.${name}`,label,type||'text')).join('')}</section>`).join('')+`<button class="add" type="button" data-add="${key}">+ 添加${title}</button>`}
function render(){
 if(!data)return;$('#tabs').innerHTML=tabs.map(([id,label])=>`<button type="button" data-tab="${id}" class="${tab===id?'active':''}">${label}</button>`).join('');let h=`<div class="form-title"><h2>${tabs.find(x=>x[0]===tab)[1]}</h2><p>填写后点击底部“保存并发布”</p></div>`;
 if(tab==='profile')h+=field('siteTitle','课题组 / 主页名称')+field('profile.name','中文姓名')+field('profile.nameEn','英文姓名')+field('profile.role','职称')+field('profile.college','单位')+field('profile.email','邮箱','email')+field('profile.office','地址')+field('profile.bio','个人简介','textarea')+imageField('profile.photo','个人照片');
 if(tab==='sidebar')h+=arrayEditor('experience','学习与工作经历')+arrayEditor('research','研究方向')+arrayEditor('teaching','教学')+arrayEditor('awards','学术荣誉和奖励')+arrayEditor('services','学术服务');
 if(tab==='news')h+=repeater('news','新闻',[['date','日期'],['author','作者'],['title','标题'],['summary','首页摘要','textarea'],['content','完整正文','textarea'],['image','新闻图片','image'],['link','相关链接','url']]);
 if(tab==='papers')h+=repeater('papers','论文',[['year','年份'],['title','论文标题'],['venue','作者与期刊 / 会议'],['content','摘要与贡献','textarea'],['link','论文链接','url']]);
 if(tab==='projects')h+=repeater('projects','项目',[['year','执行时间'],['title','项目名称'],['description','项目来源与状态'],['content','项目介绍','textarea'],['link','相关链接','url']]);
 if(tab==='students')h+=repeater('students','学生条目',[['year','年份'],['title','姓名与培养层次'],['members','研究方向 / 去向'],['content','详细介绍','textarea'],['link','相关链接','url']]);
 if(tab==='join')h+=field('join.title','招生标题')+field('join.text','招生说明','textarea');
 $('#fields').innerHTML=h;bind();
}
function arrayEditor(key,label){return `<section class="repeater"><h3>${label}</h3>${data[key].map((x,i)=>`<div class="field"><label>条目 ${i+1}<input data-array="${key}.${i}" value="${esc(x)}"></label><button class="remove" type="button" data-array-remove="${key}.${i}">删除</button></div>`).join('')}<button class="add" type="button" data-array-add="${key}">+ 添加条目</button></section>`}
function bind(){
 document.querySelectorAll('[data-tab]').forEach(e=>e.onclick=()=>{tab=e.dataset.tab;render()});document.querySelectorAll('[data-path]').forEach(e=>e.oninput=()=>set(e.dataset.path,e.value));document.querySelectorAll('[data-array]').forEach(e=>e.oninput=()=>{const [k,i]=e.dataset.array.split('.');data[k][+i]=e.value;markDirty()});
 document.querySelectorAll('[data-remove]').forEach(e=>e.onclick=()=>{const [k,i]=e.dataset.remove.split('.');data[k].splice(+i,1);markDirty();render()});document.querySelectorAll('[data-add]').forEach(e=>e.onclick=()=>{const k=e.dataset.add;const blank={news:{date:'',author:data.profile.nameEn,title:'新动态',summary:'',content:'',image:'',link:''},papers:{year:new Date().getFullYear().toString(),title:'新论文',venue:'',content:'',link:''},projects:{year:'',title:'新项目',description:'',content:'',link:''},students:{year:'',title:'新学生条目',members:'',content:'',link:''}}[k];data[k].push(blank);markDirty();render()});
 document.querySelectorAll('[data-array-remove]').forEach(e=>e.onclick=()=>{const [k,i]=e.dataset.arrayRemove.split('.');data[k].splice(+i,1);markDirty();render()});document.querySelectorAll('[data-array-add]').forEach(e=>e.onclick=()=>{data[e.dataset.arrayAdd].push('新条目');markDirty();render()});
 document.querySelectorAll('[data-upload]').forEach(e=>e.onchange=()=>{const f=e.files[0];if(!f)return;if(f.size>4*1024*1024){toast('图片请控制在 4MB 以内');return}const safe=f.name.replace(/[^a-zA-Z0-9._-]/g,'-'),path=`assets/uploads/${Date.now()}-${safe}`;pendingUploads.set(path,{file:f,dataPath:e.dataset.upload});set(e.dataset.upload,path);render()});
}
function apiConfig(){return {owner:$('#owner').value.trim(),repo:$('#repo').value.trim(),branch:$('#branch').value.trim()||'main',token:$('#token').value.trim()}}
async function gh(path,options={}){const c=apiConfig();const r=await fetch(`https://api.github.com/repos/${c.owner}/${c.repo}/${path}`,{...options,headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${c.token}`,'X-GitHub-Api-Version':'2022-11-28','Content-Type':'application/json',...(options.headers||{})}});if(!r.ok){let m='GitHub 请求失败';try{const j=await r.json();m=j.message||m}catch{}throw new Error(m)}return r.status===204?null:r.json()}
async function connect(){const c=apiConfig();if(!c.token){toast('请先填写访问令牌');return}sessionStorage.setItem('faculty-gh',JSON.stringify(c));status('正在读取仓库…');try{const f=await gh(`contents/${CONTENT_PATH}?ref=${encodeURIComponent(c.branch)}`);data=JSON.parse(decodeURIComponent(escape(atob(f.content.replace(/\n/g,'')))));sha=f.sha;dirty=false;$('#dirtyState').textContent='内容已与 GitHub 同步';status(`已连接 ${c.owner}/${c.repo} · ${c.branch}`,'ok');render()}catch(e){status(e.message,'error');toast('连接失败，请检查仓库与令牌权限')}}
function status(msg,type=''){const e=$('#connectionStatus');e.textContent=msg;e.className='status '+type}
const toBase64=file=>new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(String(r.result).split(',')[1]);r.onerror=rej;r.readAsDataURL(file)});
async function save(){if(!data)return;const c=apiConfig();if(!c.token||!sha){toast('请先连接 GitHub');return}$('#saveGithub').disabled=true;status('正在上传图片并发布…');try{for(const [path,item] of pendingUploads){await gh(`contents/${path}`,{method:'PUT',body:JSON.stringify({message:`Upload ${path}`,content:await toBase64(item.file),branch:c.branch})})}data.updatedAt=new Date().toISOString().slice(0,10);const content=btoa(unescape(encodeURIComponent(JSON.stringify(data,null,2))));const out=await gh(`contents/${CONTENT_PATH}`,{method:'PUT',body:JSON.stringify({message:`Update website content ${data.updatedAt}`,content,sha,branch:c.branch})});sha=out.content.sha;pendingUploads.clear();dirty=false;$('#dirtyState').textContent='已发布，GitHub Pages 正在更新';status('保存成功，网站通常会在 1–2 分钟内更新。','ok');toast('内容已发布')}catch(e){status(e.message,'error');toast('发布失败，请检查权限')}finally{$('#saveGithub').disabled=false}}
async function loadLocal(){try{const r=await fetch(CONTENT_PATH,{cache:'no-store'});data=await r.json();render()}catch{status('无法读取本地内容文件，请从公网网站进入管理页。','error')}}
$('#connect').onclick=connect;$('#saveGithub').onclick=save;$('#toggleHelp').onclick=()=>$('#help').hidden=!$('#help').hidden;$('#exportJson').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='faculty-homepage-content.json';a.click();URL.revokeObjectURL(a.href)};$('#importJson').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{data=JSON.parse(r.result);markDirty();render();toast('备份已导入')}catch{toast('备份文件格式错误')}};r.readAsText(f)};
const saved=sessionStorage.getItem('faculty-gh');if(saved){const c=JSON.parse(saved);$('#owner').value=c.owner;$('#repo').value=c.repo;$('#branch').value=c.branch;$('#token').value=c.token}loadLocal();
